### ISSUE TITLE
[BBU] Business Model #8: KYC for Transaction Authors

### ISSUE THREAD

**Issue by aratibaliga** [bedrock-consortium/bbu-gf#9]
## Problem/Concern

Do Transaction Endorsers need to go through KYC process for transaction authors before endorsing transactions and admitting them to the Bedrock ledger ?

**Comment by vinomaster** [comment]
TA need to sign a TAA but do not need to be LF members.

However, the TE is the final arbiter that signs (endorses) a TA trx. Since the TA will be consuming a TE entitlement (write trx) it would follow that the TE would perform some due-diligence (vetting) before performing the endorsement (maybe part of payment process). 

This is out of scope for Bedrock because the TE has a liability to BBU to make sure they do not incorrectly endorse improper writes as per TEA.
